### ISSUE TITLE
Does not work with RedirectorPage

### ISSUE THREAD

**Issue by g4b0** [briceburg/silverstripe-flexilink#1]
$Link.URL is null when a RedirectorPage is linked

**Comment by briceburg** [comment]
hey, thanks for the report. I just tested a RedirectorPage [under SS 3.1.6] and the URL method properly resolved the linked RedirectorPage. 

The method uses the Link() method for SiteTree Pages,  so providing the Link() method on your RedirectorPage class is properly resolving, it should work.

A few things to check;

What version of SS? Also, are you sure the RedirectorPage you're linking to is associated with a Page? Lastly, is 'Page' chosen for the flexilink field, with the RedirecorPage selected in the TreeDropdownField below?

**Comment by g4b0** [comment]
Sorry, my mistake. It was linking a RedirectorPage with a broken link :)
