### ISSUE TITLE
ERROR [Strict Notice]: Declaration of FlexiChoice::scaffoldFormField() should be compatible with Varchar::scaffoldFormField($title = NULL, $params = NULL)

### ISSUE THREAD

**Issue by dariuszp** [briceburg/silverstripe-flexilink#3]
```
ERROR [Strict Notice]: Declaration of FlexiChoice::scaffoldFormField() should be compatible with Varchar::scaffoldFormField($title = NULL, $params = NULL)
```

Proper declaration should be:

```
public function scaffoldFormField($title = null, $params = null)
```

//EDIT!
Ahh, sorry, this should go to FlexiChoice.

**Comment by briceburg** [comment]
Hmm what version of SilverStripe -- I remember core SS having an inconsistency here, matching the definition to what was there and bringing the issue up to the development team.  

Please do submit a PR if it's been tested on 3.1.0

Thanks!
